### ISSUE TITLE
Pass options verbatim

### ISSUE THREAD

**Issue by joscha** [substack/node-shell-quote#35] opened 2019-07-10 04:53 UTC
Any chance to get something like this:

`quote(['echo', { op: '<' }, 'file'])` to produce `echo < file` instead of `echo \< file`?
Basically a way to mark verbatim parts in the array and don't escape them.
Happy to open a PR!

**Comment by goto-bus-stop** [comment] 2019-08-13 13:37
I think this is a duplicate of #12—I think adding an `unparse()` method that has this behaviour would be nice, or adding an option to `quote` so you can do `quote([], { escapeOperators: false })`.

**Closed by goto-bus-stop** 2019-08-13 13:37 UTC
